package com.mygt.vrapp.db.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SEARCH_HISTORY".
 */
@Entity
public class SearchHistory {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String content;

    @Generated
    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    @Generated
    public SearchHistory(Long id, String content) {
        this.id = id;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(@NotNull String content) {
        this.content = content;
    }

}
